from __future__ import annotations

import uuid

from .schemas import AnalyzeRequest, AnalyzeResponse
from .stage1_behavior import Stage1BehaviorRecognizer
from .stage2_risk import Stage2RiskPredictor


class TwoStagePedestrianPipeline:
    def __init__(self) -> None:
        self.stage1 = Stage1BehaviorRecognizer()
        self.stage2 = Stage2RiskPredictor()

    def run(self, request: AnalyzeRequest) -> AnalyzeResponse:
        stage1_result = self.stage1.predict(
            video_path=request.video_path,
            pedestrian_id=request.pedestrian_id or "ped_001",
            window=16,
        )
        stage2_result = self.stage2.predict(
            behavior=stage1_result,
            include_context=request.include_context,
        )

        return AnalyzeResponse(
            request_id=str(uuid.uuid4()),
            stage1_behavior=stage1_result,
            stage2_risk=stage2_result,
            notes=[
                "Demo response generated by current inference logic.",
                "Stage 1 module can be upgraded to YOLO + CNN/LSTM.",
                "Stage 2 module can be upgraded to a trained XGBoost predictor.",
            ],
        )
